import { EventEmitter } from 'events';

const analyses = new Map();

const SAMPLES = [
  { name: 'authentic_clip', label: 'Authentic News Clip', description: 'A real news broadcast segment', type: 'video', expectedVerdict: 'LIKELY REAL' },
  { name: 'ai_generated_image', label: 'AI-Generated Portrait', description: 'A synthetic face generated by AI', type: 'image', expectedVerdict: 'LIKELY FAKE' },
  { name: 'voice_clone_false_claim', label: 'Voice-Cloned Misinformation', description: 'Real face with cloned voice making false claims', type: 'video', expectedVerdict: 'LIKELY FAKE' }
];

export function createAnalysis(id, inputInfo) {
  const analysis = {
    id,
    inputInfo,
    status: 'pending',
    agents: {},
    timestamp: Date.now(),
    emitter: new EventEmitter(),
    fusion: null,
    report: null
  };
  analyses.set(id, analysis);
  return analysis;
}

export function updateAgent(id, agentName, result) {
  const analysis = analyses.get(id);
  if (analysis) {
    analysis.agents[agentName] = result;
    analysis.emitter.emit('agent_done', { agentName, result });
  }
}

export function setFusion(id, fusionResult) {
  const analysis = analyses.get(id);
  if (analysis) {
    analysis.fusion = fusionResult;
    analysis.status = 'done';
    analysis.emitter.emit('fusion_done', fusionResult);
  }
}

export function setReport(id, report) {
  const analysis = analyses.get(id);
  if (analysis) {
    analysis.report = report;
    analysis.emitter.emit('report_done', report);
  }
}

export function getAnalysis(id) {
  return analyses.get(id);
}

export function listSamples() {
  return SAMPLES;
}

export function cleanOld() {
  const now = Date.now();
  const ONE_HOUR = 60 * 60 * 1000;
  for (const [id, analysis] of analyses.entries()) {
    if (now - analysis.timestamp > ONE_HOUR) {
      analyses.delete(id);
    }
  }
}
