import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import Upload from '../components/Upload';
import { PlayCircle, FileImage, Mic, Shield } from 'lucide-react';

const iconMap = {
  video: PlayCircle,
  image: FileImage,
  audio: Mic,
};

const Landing = () => {
  const navigate = useNavigate();
  const [samples, setSamples] = useState([]);
  const [loadingSample, setLoadingSample] = useState(null);

  useEffect(() => {
    fetch('/api/samples')
      .then(res => res.json())
      .then(data => setSamples(data))
      .catch(() => {
        // Fallback samples if backend not reachable
        setSamples([
          { name: 'authentic_clip', label: 'Authentic News Clip', description: 'A real news broadcast segment', type: 'video', expectedVerdict: 'LIKELY REAL' },
          { name: 'ai_generated_image', label: 'AI-Generated Portrait', description: 'A synthetic face generated by AI', type: 'image', expectedVerdict: 'LIKELY FAKE' },
          { name: 'voice_clone_false_claim', label: 'Voice-Cloned Misinformation', description: 'Real face with cloned voice making false claims', type: 'video', expectedVerdict: 'LIKELY FAKE' },
        ]);
      });
  }, []);

  const handleSampleClick = async (sampleName) => {
    setLoadingSample(sampleName);
    try {
      const res = await fetch(`/api/analyze/sample/${sampleName}`, { method: 'POST' });
      const data = await res.json();
      if (data.analysisId) {
        navigate(`/investigate/${data.analysisId}`);
      }
    } catch (err) {
      console.error('Failed to start sample analysis', err);
    } finally {
      setLoadingSample(null);
    }
  };

  const getVerdictStyle = (verdict) => {
    if (verdict?.includes('REAL')) return 'bg-green-500/20 text-green-400';
    if (verdict?.includes('FAKE')) return 'bg-red-500/20 text-red-400';
    return 'bg-yellow-500/20 text-yellow-400';
  };

  return (
    <div className="flex flex-col items-center justify-center min-h-[calc(100vh-130px)] px-4 py-12">
      <motion.div 
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="text-center mb-12"
      >
        <div className="flex items-center justify-center gap-3 mb-6">
          <Shield className="w-12 h-12 text-cyan-400" />
        </div>
        <h1 className="text-5xl md:text-7xl font-extrabold mb-4 text-gradient tracking-tight">
          DeepTrace
        </h1>
        <p className="text-xl text-gray-400 max-w-2xl mx-auto">
          Investigate the media. Verify the message.
        </p>
      </motion.div>

      <motion.div 
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.6, delay: 0.2 }}
        className="w-full"
      >
        <Upload />
      </motion.div>

      <motion.div 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.8, delay: 0.6 }}
        className="mt-16 w-full max-w-4xl"
      >
        <p className="text-center text-gray-500 mb-6 text-sm font-medium uppercase tracking-widest">
          Or try a sample investigation
        </p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {samples.map((sample) => {
            const Icon = iconMap[sample.type] || FileImage;
            const isLoading = loadingSample === sample.name;
            return (
              <button
                key={sample.name}
                onClick={() => handleSampleClick(sample.name)}
                disabled={isLoading}
                className="glass-panel p-5 rounded-xl text-left hover:bg-white/10 transition-all hover:-translate-y-1 hover:glow-violet group disabled:opacity-60"
              >
                <div className="flex justify-between items-start mb-3">
                  <div className="p-2 bg-violet-500/20 text-violet-400 rounded-lg group-hover:scale-110 transition-transform">
                    {isLoading ? (
                      <span className="block w-5 h-5 border-2 border-violet-300/30 border-t-violet-400 rounded-full animate-spin" />
                    ) : (
                      <Icon className="w-5 h-5" />
                    )}
                  </div>
                  <span className={`text-[10px] uppercase font-bold px-2 py-1 rounded-full ${getVerdictStyle(sample.expectedVerdict)}`}>
                    {sample.expectedVerdict}
                  </span>
                </div>
                <h3 className="font-semibold text-gray-200 mb-1">{sample.label}</h3>
                <p className="text-sm text-gray-500">{sample.description}</p>
              </button>
            );
          })}
        </div>
      </motion.div>

      <p className="mt-12 text-xs text-gray-600 max-w-lg text-center">
        Results are probabilistic. DeepTrace shows evidence, not certainty.
      </p>
    </div>
  );
};

export default Landing;
